sudo: required
services:
  - docker

before_install:
  - docker build -t clausen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true clausenc/react-test npm test -- --coverage

after_success:
  - docker build -t clausenc/multi-client ./client
  - docker build -t clausenc/multi-nginx ./nginx
  - docker build -t clausenc/multi-server ./server
  - docker build -t clausenc/multi-worker ./worker
  #Need to login
  - echo "$DOCKER_PASSWORD" | docker login -u "§DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push clausenc/multi-client
  - docker push clausenc/multi-nginx
  - docker push clausenc/multi-server
  - docker push clausenc/multi-worker
